# This module is automatically generated by autogen.sh. DO NOT EDIT.
from __future__ import annotations

from . import _Saas


class _Communication(_Saas):
    _type = "communication"
    _icon_dir = "resources/saas/communication"


class Twilio(_Communication):
    _icon = "twilio.png"


# Aliases
