# This module is automatically generated by autogen.sh. DO NOT EDIT.
from __future__ import annotations

from . import _OpenStack


class _Frontend(_OpenStack):
    _type = "frontend"
    _icon_dir = "resources/openstack/frontend"


class Horizon(_Frontend):
    _icon = "horizon.png"


# Aliases
